//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelbourneMH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender_Population
    {
        public int TypeId { get; set; }
        public string Year { get; set; }
        public Nullable<int> Male_Population { get; set; }
        public Nullable<int> Female_Population { get; set; }
        public Nullable<decimal> Male_ { get; set; }
        public Nullable<decimal> Female_ { get; set; }
    }
}
