//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelbourneMH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MelbourneMHVersion1_dbEntities : DbContext
    {
        public MelbourneMHVersion1_dbEntities()
            : base("name=MelbourneMHVersion1_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Age_Distribution> Age_Distribution { get; set; }
        public virtual DbSet<Gender_Population> Gender_Population { get; set; }
        public virtual DbSet<Melbourne_Population> Melbourne_Population { get; set; }
        public virtual DbSet<Suburb_Population> Suburb_Population { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
